server:
  port: 2000
spring:
  datasource:
    url: jdbc:mysql://47.100.7.152:3306/ejyj_system?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: javademo
    password: 123qwe!@#
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    pathmatch: # 重要！否则会报错
      matching-strategy: ant_path_matcher

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    database: 0
    host: 121.43.37.234
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:com/atqgh/system/provider/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 在控制台上打印日志
    map-underscore-to-camel-case: true

# 开启资源权限配置
#micro:
#  enableResourceSecurity: true

swagger:
  enabled: true
  title: 测试接口
  description: 描述测试接口
  version: 1.0.0
  contact:
    name: qiguohui
    url:
    email: xxx@qq.com
  package: com.atqgh.system.provider
  base-path: /**
  exclude-path: /error, /ops/**



