server:
  port: 1000
spring:
  application:
    name: ejyj-gateway
#  redis:
#    database: 0
#    host: 121.43.37.234
#    port: 6379

  cloud:
    # Sentinel熔断器
    # 网关路由配置
    gateway:
      # 这里面设置好之后，下面的routes就不用再配置了，这个地方会自动根据服务名的路径去匹配
#      discovery:
#        locator:
#          enabled: true
      # 配置路由规则
      routes:
        # 采用自定义路由ID
        - id: ejyj-system-provider-route
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
          uri: lb://ejyj-system-provider
          predicates:
            - Path=/ejyj-system/**
#            - CheckAuth=baixue
          filters:
            - StripPrefix=1
#        - id: micro-system-provider-route
#          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
#          uri: lb://micro-system-provider
#          predicates:
#            - Path=/system/**


# 配置白名单路径
#exclusion:
#  url:
#    - /auth/checkUser
#    - /auth/login
#    - /auth/logout